---
version: 0.2
phases:
  install:
    commands:
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.20.4/2021-04-12/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - export KUBECONFIG=$HOME/.kube/config
      - aws eks --region us-west-2 update-kubeconfig --name eks
      - kubectl get ns
      #- kubectl delete -f deploy-stage.yaml
      #- kubectl apply -f deploy-stage.yaml
